CREATE DATABASE usersoflogin;

CREATE TABLE loguser(
  user_id SERIAL PRIMARY KEY,
  username VARCHAR(15)UNIQUE NOT NULL,
  user_password VARCHAR(100) NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  user_role VARCHAR(10) DEFAULT 'USER'
);

CREATE TABLE article(
  article_id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  summary VARCHAR(500) NOT NULL,
  content TEXT NOT NULL,
  image_url VARCHAR(255),
  local_image_path VARCHAR(255),
  option INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
