export const labels = [ // Define the preferences array
    "Limit Live Event",
    "Theater",
    "Extreme",
    "History",
    "National Parks",
    "Beaches",
    "Caves",
    "Cliffs",
    "Mountains",
    // "Waterfalls",
    // "Islands",
    // "Forest",
    // "Entertainment Parks",
    // "Wildlife Attractions",
    // "Museums And Art Galleries",
    // "Unique Built Attractions",
    // "Sport Attractions",
    // "Participating Sport Attractions",
    // "Stadium Tours",
    // "Special Events",
    // "Markets",
    // "Festivals And Parades",
    "Exhibitions"
];